In [25]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt
from matplotlib.ticker import StrMethodFormatter
import platform
import re
from pathlib import Path

if platform.system() == "Darwin":   # macOS
    plt.rcParams["font.family"] = "AppleGothic"
else:                               # Windows / Linux
    plt.rcParams["font.family"] = "Malgun Gothic"

plt.rcParams["axes.unicode_minus"] = False

In [26]:
df = pd.read_csv("/Users/restitutor/Documents/Restitutor/Workspace/Flutter-Python/Python/Team_PL/Data/한강공원 주차장 일별 이용 현황.csv", encoding="cp949")
df[df["지구별"] == "PLT-008"]

           지구별     주차장명  주차대수    이용시간          날짜
4      PLT-008  여의도2주차장  2201  180181  2026/04/01
6      PLT-008  여의도5주차장   420  109189  2026/04/01
7      PLT-008  여의도4주차장   414   67081  2026/04/01
15     PLT-008  여의도1주차장  2621  394329  2026/04/01
20     PLT-008  여의도3주차장  2891  445738  2026/04/01
...        ...      ...   ...     ...         ...
59455  PLT-008  여의도1주차장  1541  172802  2020/01/18
59460  PLT-008  여의도1주차장  1113  255747  2020/01/17
59467  PLT-008  여의도1주차장   873  221484  2020/01/16
59468  PLT-008  여의도1주차장   114    6073  2020/01/15
59470  PLT-008  여의도1주차장     2       0  2020/01/14

[11215 rows x 5 columns]

In [27]:
df["year"] = pd.to_datetime(df["날짜"]).dt.year
df["month"] = pd.to_datetime(df["날짜"]).dt.month
df["day"] = pd.to_datetime(df["날짜"]).dt.day
df.drop(
    columns=["날짜","이용시간"],
    inplace=True
)
df.head()

       지구별     주차장명  주차대수  year  month  day
0  PLT-007   양화1주차장   255  2026      4    1
1  PLT-007   양화2주차장    71  2026      4    1
2  PLT-010   잠원1주차장   600  2026      4    1
3  PLT-006  광나루4주차장   306  2026      4    1
4  PLT-008  여의도2주차장  2201  2026      4    1

In [41]:
import holidays

kr_holidays = holidays.KR(years=[2023, 2024, 2025])
df["날짜"] = pd.to_datetime(df[["year", "month", "day"]])
df["날짜 타입"] = df["날짜"].apply(
    lambda x: "휴일" if (x.weekday() >= 5 or x.date() in kr_holidays) else "평일"
)

sp = df[(df["지구별"] == "PLT-008") & (df["year"] >= 2023) & (df["year"] < 2026)]
sp.drop(
    columns=["지구별", "month", "day", "날짜"],
    inplace=True
)

In [43]:
tYear = [2023, 2024, 2025]
for y in tYear:\
sp[sp["year"] == y].reset_index(
    drop=True,
).to_csv(f"../Data/Target_{y}_raw.csv", index=False)